import { useState } from 'react'
import './App.css'

// ─── Week data ──────────────────────────────────────────────────────────────
// Update this array each week.
// Set live: true and add url + githubUrl when the app is deployed.
interface Week {
  week: number
  title: string
  description: string
  url: string        // deployed app URL
  githubUrl: string  // GitHub repo for this week
  live: boolean      // manually flip to true when app is deployed
  liveDate: string   // YYYY-MM-DD — card becomes flippable on this date
}

const START_DATE = '2026-03-08'

function getWeekLiveDate(weekNum: number): string {
  const [y, m, d] = START_DATE.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + (weekNum - 1) * 7)
  const yy = date.getFullYear()
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${yy}-${mm}-${dd}`
}

const weeks: Week[] = [
  {
    week: 1,
    title: 'The Planner',
    description: 'Track and plan all 52 builds',
    url: 'https://week01-the-planner.vercel.app/week01/',
    githubUrl: 'https://github.com/hayimpapa/week01-the-planner',
    live: true,
    liveDate: '2026-03-08',
  },
  {
    week: 2,
    title: 'Receipt Scanner & Analyser',
    description: 'Scan receipts and analyse grocery and shopping spending',
    url: 'https://week02-receipt-scan-and-analyse.vercel.app/week02',
    githubUrl: 'https://github.com/hayimpapa/week02-receipt-analyser',
    live: true,
    liveDate: '2026-03-15',
  },
  {
    week: 3,
    title: 'Flappy Tram',
    description: 'A flappy bird style game with Melbourne trams',
    url: 'https://week03-flappy-tram.vercel.app/',
    githubUrl: 'https://github.com/hayimpapa/week03-flappy-tram',
    live: true,
    liveDate: '2026-03-22',
  },
  {
    week: 4,
    title: 'Math Monsters',
    description: 'A monster-themed maths game for kids aged 5–10',
    url: 'https://week04-mathmonsters.vercel.app/',
    githubUrl: 'https://github.com/hayimpapa/week04-mathmonsters',
    live: true,
    liveDate: getWeekLiveDate(4),
  },
  {
    week: 5,
    title: 'Meno Mano',
    description: 'Meno Mano - an easy game, inspired by La Linea',
    url: 'https://week05-menomano.vercel.app/',
    githubUrl: 'https://github.com/hayimpapa/week05-menomano',
    live: true,
    liveDate: getWeekLiveDate(5),
  },
  {
    week: 6,
    title: 'Squad Health',
    description: 'A Spotify-inspired squad health check for agile teams',
    url: 'https://week06-agile-team-health-check.vercel.app/',
    githubUrl: 'https://github.com/hayimpapa/week06-agile-team-health-check',
    live: true,
    liveDate: getWeekLiveDate(6),
  },
  {
    week: 7,
    title: 'Meeting Prep Coach',
    description: 'Your AI sparring partner for sharper meetings',
    url: 'https://week07-meeting-prep.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(7),
  },
  {
    week: 8,
    title: 'LinguaFlip',
    description: 'A minimal flashcard app for learning Indonesian with spaced repetition',
    url: 'https://week08-language-flashcards.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(8),
  },
  {
    week: 9,
    title: 'Suburb Match',
    description: 'A cheeky Melbourne suburb recommender — tell us your vibe and find your spiritual home',
    url: 'https://week09-melbourne-suburbs.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(9),
  },
  {
    week: 10,
    title: 'Portfolio Pulse',
    description: 'A mobile-first portfolio tracker with live Yahoo Finance prices, persisted to localStorage',
    url: 'https://week10-investment-tracker.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(10),
  },
  {
    week: 11,
    title: 'Certified, Not Stupid',
    description: 'A meme certificate generator — pick from 100 ironic certifications, add your name, and download as PDF, PNG, or email',
    url: 'https://certified-not-stupid.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(11),
  },
  {
    week: 12,
    title: 'Zendu',
    description: 'Pick a short learning path. Watch a few modules. Finish with an AI-generated quiz to see what stuck.',
    url: 'https://week12-zendu.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(12),
  },
  {
    week: 13,
    title: 'Khmer Flashcards',
    description: 'A minimal flashcard app for learning Khmer with spaced repetition',
    url: 'https://khmer-flashcards.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(13),
  },
  {
    week: 14,
    title: 'Weekly Meal Planner',
    description: 'Personalised 7-day meal plans, generated by Claude',
    url: 'https://week14-mealplanner.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(14),
  },
  {
    week: 15,
    title: 'Portfolio Rebalancer',
    description: 'A backend-free portfolio rebalancer — set target allocations, add holdings, and get color-coded suggestions with live prices and charts',
    url: 'https://week15-portfolio-balancer.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(15),
  },
  {
    week: 16,
    title: 'Pálinka Panic',
    description: 'A catch-the-falling-things arcade game with every sprite hand-drawn on Canvas — pure Hungarian chaos, synthesised sound, no image files',
    url: 'https://palinka-panic.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(16),
  },
  {
    week: 17,
    title: 'Myki Madness',
    description: 'A Melbourne endless-runner about sprinting for a closing tram — every pixel drawn in code, every sound synthesised live',
    url: 'https://myki-madness.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(17),
  },
  {
    week: 18,
    title: 'Highway Hitchhiker',
    description: 'A retro arcade game — pick up a passenger and drop them off while dodging obstacles down the highway',
    url: 'https://highway-quartz.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(18),
  },
  {
    week: 19,
    title: 'Melbourne Fuel Finder',
    description: "Live 91 Unleaded petrol prices across Melbourne, powered by Service Victoria's fuel price API",
    url: 'https://week19-melbourne-fuel-prices.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(19),
  },
  {
    week: 20,
    title: 'Nightshift',
    description: 'A simple biohack app to log sleep and cardio activity on a daily basis, saved in localStorage',
    url: 'https://biohack-mini.vercel.app/',
    githubUrl: '',
    live: true,
    liveDate: getWeekLiveDate(20),
  },
  // Weeks 21–52: fill in title/description/url/githubUrl each week
  ...Array.from({ length: 32 }, (_, i) => ({
    week: i + 21,
    title: '',
    description: '',
    url: '',
    githubUrl: '',
    live: false,
    liveDate: getWeekLiveDate(i + 21),
  })),
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

// Parse a YYYY-MM-DD string as a LOCAL date (avoids UTC off-by-one)
function parseLocalDate(dateStr: string): Date {
  const [y, m, d] = dateStr.split('-').map(Number)
  return new Date(y, m - 1, d)
}

function localToday(): Date {
  const now = new Date()
  return new Date(now.getFullYear(), now.getMonth(), now.getDate())
}

// Card is flippable when its scheduled date has arrived (regardless of live flag)
function isDateUnlocked(w: Week): boolean {
  const today = localToday()
  const scheduled = parseLocalDate(w.liveDate)
  return today >= scheduled
}

// Card shows full Launch + GitHub buttons only when manually marked live AND date arrived
function isFullyLive(w: Week): boolean {
  return w.live && isDateUnlocked(w)
}

function formatWeekDate(dateStr: string): string {
  const d = parseLocalDate(dateStr)
  return d.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

// ─── Icons ────────────────────────────────────────────────────────────────────

function GitHubIcon({ size = 20 }: { size?: number }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
    >
      <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0 1 12 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" />
    </svg>
  )
}

function LockIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="22"
      height="22"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}

// ─── Card Icons ──────────────────────────────────────────────────────────────

function CalendarIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="8" y="14" width="48" height="42" rx="6" stroke="currentColor" strokeWidth="2.5" />
      <path d="M8 26h48" stroke="currentColor" strokeWidth="2.5" />
      <path d="M20 8v12M44 8v12" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <rect x="16" y="32" width="8" height="6" rx="1.5" fill="currentColor" opacity="0.25" />
      <rect x="28" y="32" width="8" height="6" rx="1.5" fill="currentColor" opacity="0.25" />
      <rect x="40" y="32" width="8" height="6" rx="1.5" fill="currentColor" opacity="0.25" />
      <rect x="16" y="42" width="8" height="6" rx="1.5" fill="currentColor" opacity="0.25" />
      <rect x="28" y="42" width="8" height="6" rx="1.5" fill="currentColor" opacity="0.4" />
    </svg>
  )
}

function ReceiptScanIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <path d="M16 8l4 4 4-4 4 4 4-4 4 4 4-4 4 4 4-4v48l-4-4-4 4-4-4-4 4-4-4-4 4-4-4-4 4V8z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" />
      <path d="M24 22h16M24 30h12M24 38h14" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <rect x="2" y="26" width="60" height="4" rx="2" fill="currentColor" opacity="0.18" />
      <path d="M6 28h52" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeDasharray="2 3" opacity="0.5" />
    </svg>
  )
}

function TramIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="14" y="16" width="36" height="36" rx="8" stroke="currentColor" strokeWidth="2.5" />
      <path d="M14 36h36" stroke="currentColor" strokeWidth="2.5" />
      <rect x="20" y="22" width="10" height="10" rx="2" stroke="currentColor" strokeWidth="2" opacity="0.5" />
      <rect x="34" y="22" width="10" height="10" rx="2" stroke="currentColor" strokeWidth="2" opacity="0.5" />
      <circle cx="24" cy="44" r="3" fill="currentColor" opacity="0.35" />
      <circle cx="40" cy="44" r="3" fill="currentColor" opacity="0.35" />
      <path d="M32 6v10" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M22 6h20" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M20 52l-4 6M44 52l4 6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
    </svg>
  )
}

function MathMonsterIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <ellipse cx="32" cy="36" rx="22" ry="20" stroke="currentColor" strokeWidth="2.5" />
      <circle cx="24" cy="32" r="5" stroke="currentColor" strokeWidth="2" />
      <circle cx="40" cy="32" r="5" stroke="currentColor" strokeWidth="2" />
      <circle cx="24" cy="32" r="2" fill="currentColor" opacity="0.5" />
      <circle cx="40" cy="32" r="2" fill="currentColor" opacity="0.5" />
      <path d="M26 44c2 2 8 2 12 0" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M22 16c-2-6 2-10 4-8M42 16c2-6-2-10-4-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <text x="14" y="12" fontSize="10" fontWeight="bold" fill="currentColor" opacity="0.3" fontFamily="Georgia, serif">+</text>
      <text x="44" y="12" fontSize="10" fontWeight="bold" fill="currentColor" opacity="0.3" fontFamily="Georgia, serif">=</text>
      <text x="4" y="42" fontSize="10" fontWeight="bold" fill="currentColor" opacity="0.2" fontFamily="Georgia, serif">÷</text>
      <text x="54" y="42" fontSize="10" fontWeight="bold" fill="currentColor" opacity="0.2" fontFamily="Georgia, serif">×</text>
    </svg>
  )
}

function MenoManoIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <path d="M8 52c8-2 14-4 20-4s12 2 20 4" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <circle cx="32" cy="24" r="10" stroke="currentColor" strokeWidth="2.5" />
      <circle cx="29" cy="22" r="2" fill="currentColor" opacity="0.5" />
      <circle cx="35" cy="22" r="2" fill="currentColor" opacity="0.5" />
      <path d="M28 28c1.5 1.5 4.5 1.5 6 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <path d="M32 34v8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M32 42l-6 6M32 42l6 6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M32 37l-8-3M32 37l8-3" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M42 14c2-4 6-4 8-2" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.3" />
    </svg>
  )
}

function SquadHealthIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="10" y="8" width="44" height="48" rx="6" stroke="currentColor" strokeWidth="2.5" />
      <circle cx="20" cy="20" r="4" fill="currentColor" opacity="0.75" />
      <circle cx="20" cy="32" r="4" fill="currentColor" opacity="0.5" />
      <circle cx="20" cy="44" r="4" fill="currentColor" opacity="0.3" />
      <path d="M28 20h18M28 32h14M28 44h16" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M40 54c-1-4 2-7 5-7s6 3 5 7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.4" />
    </svg>
  )
}

function MeetingPrepIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <path d="M10 16c0-4 2-6 6-6h32c4 0 6 2 6 6v24c0 4-2 6-6 6H28l-8 8v-8h-4c-4 0-6-2-6-6V16z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" />
      <path d="M18 22h24M18 28h18M18 34h22" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.45" />
      <text x="48" y="60" fontSize="16" fontWeight="bold" fill="currentColor" opacity="0.4" fontFamily="Georgia, serif">?</text>
      <text x="4" y="18" fontSize="12" fontWeight="bold" fill="currentColor" opacity="0.25" fontFamily="Georgia, serif">?</text>
      <text x="54" y="14" fontSize="10" fontWeight="bold" fill="currentColor" opacity="0.2" fontFamily="Georgia, serif">?</text>
    </svg>
  )
}

function FlashcardIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="6" y="18" width="40" height="28" rx="4" stroke="currentColor" strokeWidth="2.5" transform="rotate(-8 26 32)" opacity="0.45" />
      <rect x="18" y="18" width="40" height="28" rx="4" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.06" transform="rotate(6 38 32)" />
      <text x="30" y="38" fontSize="14" fontWeight="bold" fill="currentColor" fontFamily="Georgia, serif" transform="rotate(6 38 32)">A</text>
      <text x="44" y="38" fontSize="10" fill="currentColor" opacity="0.55" fontFamily="Georgia, serif" transform="rotate(6 38 32)">あ</text>
      <path d="M10 10c4-2 8-2 12 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
      <path d="M22 10l-3-2M22 10l-2 3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
      <path d="M54 56c-4 2-8 2-12 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
      <path d="M42 56l3 2M42 56l2-3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
    </svg>
  )
}

function SuburbMatchIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="6" y="14" width="52" height="40" rx="4" stroke="currentColor" strokeWidth="2.5" />
      <path d="M6 28h52M6 42h52" stroke="currentColor" strokeWidth="1.5" opacity="0.3" />
      <path d="M22 14v40M44 14v40" stroke="currentColor" strokeWidth="1.5" opacity="0.3" />
      <path d="M32 16c-5 0-9 4-9 9 0 7 9 17 9 17s9-10 9-17c0-5-4-9-9-9z" fill="currentColor" fillOpacity="0.18" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" />
      <path d="M32 28c-1-1.8-4-1.8-4 0.4 0 2 4 3.8 4 3.8s4-1.8 4-3.8c0-2.2-3-2.2-4-0.4z" fill="currentColor" opacity="0.65" />
      <circle cx="13" cy="22" r="1.8" fill="currentColor" opacity="0.4" />
      <circle cx="51" cy="48" r="1.8" fill="currentColor" opacity="0.4" />
      <circle cx="50" cy="20" r="1.4" fill="currentColor" opacity="0.3" />
    </svg>
  )
}

function PortfolioPulseIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="16" y="6" width="32" height="52" rx="5" stroke="currentColor" strokeWidth="2.5" />
      <rect x="20" y="13" width="24" height="34" rx="2" stroke="currentColor" strokeWidth="1.5" opacity="0.45" />
      <path d="M22 38l5-6 5 4 5-10 5 4" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
      <circle cx="42" cy="26" r="1.6" fill="currentColor" />
      <path d="M42 24v-5m0 0l-2.5 2.5m2.5-2.5l2.5 2.5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" opacity="0.55" />
      <circle cx="32" cy="52" r="2" fill="currentColor" opacity="0.5" />
      <text x="22" y="20" fontSize="6" fontWeight="bold" fill="currentColor" opacity="0.45" fontFamily="Georgia, serif">$</text>
    </svg>
  )
}

function CertificateIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <circle cx="32" cy="26" r="14" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.08" />
      <circle cx="32" cy="26" r="9" stroke="currentColor" strokeWidth="1.5" opacity="0.45" />
      <path d="M32 19l2.2 4.6 5 .7-3.6 3.5.9 5-4.5-2.4-4.5 2.4.9-5L24.8 24.3l5-.7z" fill="currentColor" opacity="0.75" />
      <path d="M22 38l-4 18 8-4 6 4 6-4 8 4-4-18" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round" fill="currentColor" fillOpacity="0.1" />
      <path d="M14 12h8M14 16h6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.3" />
      <path d="M50 12h-8M50 16h-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.3" />
    </svg>
  )
}

function ZenduIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <path d="M8 48c6-2 10-10 16-10s10 8 16 8 8-6 16-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.45" strokeDasharray="3 4" />
      <circle cx="12" cy="46" r="4" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.15" />
      <circle cx="32" cy="40" r="4" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.15" />
      <rect x="20" y="8" width="24" height="18" rx="3" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.08" />
      <path d="M29 13l8 4-8 4z" fill="currentColor" opacity="0.7" />
      <circle cx="52" cy="44" r="9" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.15" />
      <text x="48.5" y="48.5" fontSize="11" fontWeight="bold" fill="currentColor" fontFamily="Georgia, serif">?</text>
    </svg>
  )
}

function KhmerFlashcardIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="6" y="18" width="40" height="28" rx="4" stroke="currentColor" strokeWidth="2.5" transform="rotate(-8 26 32)" opacity="0.45" />
      <rect x="18" y="18" width="40" height="28" rx="4" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.06" transform="rotate(6 38 32)" />
      <text x="30" y="38" fontSize="14" fontWeight="bold" fill="currentColor" fontFamily="Georgia, serif" transform="rotate(6 38 32)">A</text>
      <text x="42" y="40" fontSize="16" fill="currentColor" opacity="0.7" fontFamily="serif" transform="rotate(6 38 32)">ក</text>
      <path d="M10 10c4-2 8-2 12 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
      <path d="M22 10l-3-2M22 10l-2 3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5" />
      <path d="M50 8c2 1 3 3 3 5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.4" />
      <circle cx="56" cy="14" r="1.5" fill="currentColor" opacity="0.4" />
    </svg>
  )
}

function MealPlannerIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      <rect x="8" y="10" width="48" height="44" rx="5" stroke="currentColor" strokeWidth="2.5" />
      <path d="M8 22h48" stroke="currentColor" strokeWidth="2" opacity="0.5" />
      <path d="M22 22v32M36 22v32M50 22v32" stroke="currentColor" strokeWidth="1.2" opacity="0.3" />
      <path d="M8 34h48M8 44h48" stroke="currentColor" strokeWidth="1.2" opacity="0.3" />
      <circle cx="15" cy="28" r="3" fill="currentColor" opacity="0.55" />
      <circle cx="29" cy="39" r="3" stroke="currentColor" strokeWidth="1.8" opacity="0.55" />
      <path d="M43 36l4 6h-8z" fill="currentColor" opacity="0.55" />
      <circle cx="15" cy="49" r="2.5" stroke="currentColor" strokeWidth="1.8" opacity="0.45" />
      <rect x="40" y="46" width="8" height="6" rx="1" fill="currentColor" opacity="0.4" />
      <path d="M20 6v8M44 6v8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <circle cx="54" cy="14" r="6" fill="currentColor" fillOpacity="0.08" stroke="currentColor" strokeWidth="1.8" />
      <path d="M52 12l1.5 1.5L57 10" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function PortfolioBalancerIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* balance beam + pivot */}
      <path d="M32 12v34" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M12 18h40" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <circle cx="32" cy="12" r="2.5" fill="currentColor" opacity="0.6" />
      <path d="M24 52h16" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      {/* left pan (under-target) */}
      <path d="M6 18l6 12h0M18 18l-6 12" stroke="currentColor" strokeWidth="1.5" opacity="0.5" />
      <path d="M5 30a7 7 0 0 0 14 0z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="currentColor" fillOpacity="0.1" />
      {/* right pan (over-target) */}
      <path d="M46 18l6 14h0M58 18l-6 14" stroke="currentColor" strokeWidth="1.5" opacity="0.5" />
      <path d="M44 32a8 8 0 0 0 16 0z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="currentColor" fillOpacity="0.18" />
      {/* pie chart of target allocation */}
      <circle cx="32" cy="44" r="2" fill="currentColor" opacity="0.4" />
      <text x="9" y="14" fontSize="8" fontWeight="bold" fill="currentColor" opacity="0.4" fontFamily="Georgia, serif">$</text>
      <text x="49" y="14" fontSize="8" fontWeight="bold" fill="currentColor" opacity="0.4" fontFamily="Georgia, serif">%</text>
    </svg>
  )
}

function PalinkaPanicIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* Falling pálinka bottle */}
      <rect x="28" y="6" width="8" height="3" rx="1" fill="currentColor" opacity="0.6" />
      <path d="M27 9h10l2 6H25z" fill="currentColor" opacity="0.5" />
      <rect x="24" y="15" width="16" height="20" rx="3" stroke="currentColor" strokeWidth="2" fill="currentColor" fillOpacity="0.12" />
      <path d="M27 20h10M27 25h10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity="0.4" />
      {/* Folk art diamond on bottle */}
      <path d="M32 22l2 2-2 2-2-2z" fill="currentColor" opacity="0.55" />
      {/* Falling drops / smaller bottles */}
      <circle cx="14" cy="18" r="3.5" stroke="currentColor" strokeWidth="1.8" fill="currentColor" fillOpacity="0.1" opacity="0.7" />
      <circle cx="52" cy="28" r="2.5" stroke="currentColor" strokeWidth="1.8" fill="currentColor" fillOpacity="0.1" opacity="0.55" />
      <circle cx="10" cy="36" r="2" fill="currentColor" opacity="0.3" />
      {/* Catcher basket at bottom */}
      <path d="M10 54h44" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      <path d="M14 54V48c0-2 2-3 4-3h28c2 0 4 1 4 3v6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" fill="currentColor" fillOpacity="0.08" />
      {/* Basket weave lines */}
      <path d="M22 45v9M32 45v9M42 45v9" stroke="currentColor" strokeWidth="1" opacity="0.3" />
      <path d="M14 49h36" stroke="currentColor" strokeWidth="1" opacity="0.3" />
      {/* Hungarian folk tulip accent */}
      <path d="M54 10c0-3 3-5 3-5s3 2 3 5-3 4-3 4-3-1-3-4z" fill="currentColor" opacity="0.3" />
      <path d="M57 15v5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity="0.3" />
      <path d="M55 18c-1 0-2 1-2 2M59 18c1 0 2 1 2 2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" opacity="0.25" />
    </svg>
  )
}

function MykiMadnessIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* Tram racing away — doors closing */}
      <rect x="20" y="12" width="34" height="30" rx="6" stroke="currentColor" strokeWidth="2.5" fill="currentColor" fillOpacity="0.06" />
      <path d="M20 30h34" stroke="currentColor" strokeWidth="2" opacity="0.5" />
      {/* Closing doors gap */}
      <path d="M37 12v18" stroke="currentColor" strokeWidth="1.5" strokeDasharray="2 2" opacity="0.5" />
      <rect x="26" y="18" width="8" height="8" rx="1.5" stroke="currentColor" strokeWidth="1.8" opacity="0.5" />
      <rect x="40" y="18" width="8" height="8" rx="1.5" stroke="currentColor" strokeWidth="1.8" opacity="0.5" />
      <circle cx="30" cy="36" r="2.5" fill="currentColor" opacity="0.35" />
      <circle cx="46" cy="36" r="2.5" fill="currentColor" opacity="0.35" />
      <path d="M37 4v8M28 6h18" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      {/* Motion / speed lines */}
      <path d="M4 20h9M2 27h11M4 34h9" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.55" />
      {/* Commuter sprinting on the platform */}
      <circle cx="12" cy="48" r="3.5" stroke="currentColor" strokeWidth="2.2" />
      <path d="M12 51.5l-2 7M12 54l6 3M12 54l-5 4M12 53l7-2" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" />
      {/* Platform line */}
      <path d="M6 60h52" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" opacity="0.4" />
    </svg>
  )
}

function HighwayHitchhikerIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* Highway receding to horizon (perspective) */}
      <path d="M24 58L30 14h4l6 44z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="currentColor" fillOpacity="0.06" />
      {/* Dashed lane markings */}
      <path d="M32 20v3M32 28v4M32 38v5M32 49v6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.55" />
      {/* Horizon line */}
      <path d="M14 14h36" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.3" />
      {/* Retro sun on the horizon */}
      <circle cx="46" cy="12" r="5" stroke="currentColor" strokeWidth="2" fill="currentColor" fillOpacity="0.12" opacity="0.6" />
      <path d="M41 11h10M42 14h8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" opacity="0.5" />
      {/* Player car near the bottom */}
      <path d="M20 52c0-2 1-4 3-4h6c2 0 3 2 3 4v5c0 1-1 2-2 2H22c-1 0-2-1-2-2z" stroke="currentColor" strokeWidth="2.2" strokeLinejoin="round" fill="currentColor" fillOpacity="0.1" />
      <path d="M22 51h8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity="0.5" />
      <circle cx="23" cy="59" r="1.6" fill="currentColor" opacity="0.5" />
      <circle cx="29" cy="59" r="1.6" fill="currentColor" opacity="0.5" />
      {/* Obstacle further up the road (cone) */}
      <path d="M36 40l2-6 2 6z" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round" fill="currentColor" fillOpacity="0.15" opacity="0.7" />
      {/* Hitchhiker on the roadside, thumb out */}
      <circle cx="10" cy="30" r="3" stroke="currentColor" strokeWidth="2" />
      <path d="M10 33v9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <path d="M10 42l-3 6M10 42l3 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <path d="M10 36l6-3M16 33l1-3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

function FuelFinderIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* Petrol pump body */}
      <path d="M14 56V18a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v38" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" />
      <path d="M10 56h28" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
      {/* Display showing the fuel grade */}
      <rect x="17" y="19" width="14" height="11" rx="2" stroke="currentColor" strokeWidth="2" fill="currentColor" fillOpacity="0.1" />
      <text x="24" y="27.5" fontSize="8" fontWeight="bold" fill="currentColor" textAnchor="middle" fontFamily="Georgia, serif">91</text>
      {/* Price rows */}
      <path d="M18 35h12M18 40h8" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" opacity="0.4" />
      {/* Hose feeding the nozzle */}
      <path d="M32 22h5a3 3 0 0 1 3 3v6" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.55" />
      {/* Location pin with a fuel drop — the "finder" */}
      <path d="M48 12c-5 0-9 4-9 9 0 6 9 16 9 16s9-10 9-16c0-5-4-9-9-9z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="currentColor" fillOpacity="0.12" />
      <path d="M48 16c-2 3-3.5 4.5-3.5 6.5a3.5 3.5 0 0 0 7 0c0-2-1.5-3.5-3.5-6.5z" fill="currentColor" opacity="0.65" />
    </svg>
  )
}

function NightshiftIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none" className="card-icon" aria-hidden="true">
      {/* Crescent moon — sleep / night */}
      <path d="M42 8a20 20 0 1 0 14 30 16 16 0 0 1-14-30z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="currentColor" fillOpacity="0.08" />
      {/* Cardio pulse / heartbeat line across the middle */}
      <path d="M6 44h9l4-9 6 18 5-13 4 8 5-5h14" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
      {/* Small heart marking the cardio beat */}
      <path d="M50 40c-1-1.6-3.6-1.6-3.6.4 0 1.8 3.6 3.4 3.6 3.4s3.6-1.6 3.6-3.4c0-2-2.6-2-3.6-.4z" fill="currentColor" opacity="0.6" />
      {/* Stars / sleepy sparkle */}
      <path d="M14 14l1.2 3 3 1.2-3 1.2L14 22l-1.2-2.6-3-1.2 3-1.2z" fill="currentColor" opacity="0.5" />
      <circle cx="26" cy="10" r="1.6" fill="currentColor" opacity="0.4" />
      <circle cx="8" cy="28" r="1.4" fill="currentColor" opacity="0.3" />
      {/* "Z" for sleep */}
      <path d="M52 52h7l-7 7h7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity="0.45" />
    </svg>
  )
}

function getCardIcon(weekNum: number) {
  switch (weekNum) {
    case 1: return <CalendarIcon />
    case 2: return <ReceiptScanIcon />
    case 3: return <TramIcon />
    case 4: return <MathMonsterIcon />
    case 5: return <MenoManoIcon />
    case 6: return <SquadHealthIcon />
    case 7: return <MeetingPrepIcon />
    case 8: return <FlashcardIcon />
    case 9: return <SuburbMatchIcon />
    case 10: return <PortfolioPulseIcon />
    case 11: return <CertificateIcon />
    case 12: return <ZenduIcon />
    case 13: return <KhmerFlashcardIcon />
    case 14: return <MealPlannerIcon />
    case 15: return <PortfolioBalancerIcon />
    case 16: return <PalinkaPanicIcon />
    case 17: return <MykiMadnessIcon />
    case 18: return <HighwayHitchhikerIcon />
    case 19: return <FuelFinderIcon />
    case 20: return <NightshiftIcon />
    default: return null
  }
}

function ExternalLinkIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="13"
      height="13"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" y1="14" x2="21" y2="3" />
    </svg>
  )
}

// ─── Flip Card ────────────────────────────────────────────────────────────────

function WeekCard({ w }: { w: Week }) {
  const [flipped, setFlipped] = useState(false)
  const dateOpen = isDateUnlocked(w)
  const fullyLive = isFullyLive(w)
  const weekLabel = `W${String(w.week).padStart(2, '0')}`

  function handleClick() {
    if (dateOpen) setFlipped(f => !f)
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      handleClick()
    }
  }

  return (
    <div
      className={`card-wrapper${dateOpen ? ' card-unlocked' : ''}`}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      tabIndex={dateOpen ? 0 : -1}
      role={dateOpen ? 'button' : undefined}
      aria-label={
        dateOpen
          ? `Week ${w.week}${w.title ? ': ' + w.title : ''}. Click to flip.`
          : `Week ${w.week}: coming ${formatWeekDate(w.liveDate)}`
      }
      aria-pressed={dateOpen ? flipped : undefined}
    >
      <div className={`card-inner${flipped ? ' flipped' : ''}`}>
        {/* ── FRONT ── */}
        <div className={`card-face card-front${dateOpen ? ' card-front--live' : ''}`}>
          <span className="card-week-num">{weekLabel}</span>
          {!dateOpen && (
            <span className="card-lock">
              <LockIcon />
            </span>
          )}
          {dateOpen && w.title && (
            <span className="card-front-title">{w.title}</span>
          )}
          {dateOpen && getCardIcon(w.week)}
          {dateOpen && (
            <span className="card-flip-hint">tap to flip</span>
          )}
        </div>

        {/* ── BACK ── */}
        <div className="card-face card-back">
          {fullyLive ? (
            // Live: show app details + two action buttons
            <div className="card-back-live">
              <span className="card-back-week-label">Week {w.week}</span>
              <h3 className="card-back-title">{w.title}</h3>
              <p className="card-back-desc">{w.description}</p>
              <div className="card-back-actions">
                {w.url && (
                  <a
                    href={w.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="card-launch-btn"
                    onClick={e => e.stopPropagation()}
                    tabIndex={flipped ? 0 : -1}
                  >
                    Launch App <ExternalLinkIcon />
                  </a>
                )}
                {w.githubUrl && (
                  <a
                    href={w.githubUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="card-github-btn"
                    aria-label="View on GitHub"
                    onClick={e => e.stopPropagation()}
                    tabIndex={flipped ? 0 : -1}
                  >
                    <GitHubIcon size={16} />
                  </a>
                )}
              </div>
            </div>
          ) : dateOpen ? (
            // Date arrived but not yet manually marked live
            <div className="card-back-coming-soon">
              <span className="card-back-week-label card-back-week-label--muted">Week {w.week}</span>
              {w.title && <h3 className="card-back-title card-back-title--muted">{w.title}</h3>}
              <p className="card-coming">Coming soon</p>
              <p className="card-not-yet">Not live yet — check back soon</p>
            </div>
          ) : (
            // Date not yet reached
            <div className="card-back-locked">
              <span className="card-back-week-label card-back-week-label--muted">Week {w.week}</span>
              <p className="card-coming">Coming week of</p>
              <p className="card-coming-date">{formatWeekDate(w.liveDate)}</p>
              <p className="card-not-yet">Not built yet — check back soon</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Progress Bar ─────────────────────────────────────────────────────────────

function ProgressBar({ total, done }: { total: number; done: number }) {
  const pct = Math.round((done / total) * 100)
  return (
    <div className="progress-wrap">
      <div className="progress-labels">
        <span className="progress-count">
          <strong>{done}</strong> of {total} apps live
        </span>
        <span className="progress-pct">{pct}%</span>
      </div>
      <div className="progress-track" role="progressbar" aria-valuenow={done} aria-valuemin={0} aria-valuemax={total}>
        <div className="progress-fill" style={{ width: `${pct}%` }} />
      </div>
    </div>
  )
}

// ─── App ─────────────────────────────────────────────────────────────────────

export default function App() {
  const liveCount = weeks.filter(isFullyLive).length

  return (
    <div className="page">
      {/* ── Header ── */}
      <header className="header">
        <div className="header-inner">
          <h1 className="header-title">
            52 apps.<br />52 weeks.<br />Before I turn 52.
          </h1>
          <p className="header-bio">
            I'm Gabor. I turned 51 and made myself a slightly ridiculous promise.
            Every week for a year I'll build one app from scratch using AI tools —
            no traditional coding background, just curiosity and a problem worth
            solving. This is what that looks like, honestly, week by week.
          </p>
          <a
            href="https://github.com/hayimpapa"
            target="_blank"
            rel="noopener noreferrer"
            className="github-btn"
          >
            <GitHubIcon />
            GitHub
          </a>
          <ProgressBar total={52} done={liveCount} />
        </div>
      </header>

      {/* ── Grid ── */}
      <main className="main">
        <div className="grid">
          {weeks.map(w => (
            <WeekCard key={w.week} w={w} />
          ))}
        </div>
      </main>

      {/* ── Footer ── */}
      <footer className="footer">
        <p className="footer-name">Built by Gabor</p>
        <a
          href="https://github.com/hayimpapa"
          target="_blank"
          rel="noopener noreferrer"
          className="footer-link"
        >
          <GitHubIcon />
          github.com/hayimpapa
        </a>
        <p className="footer-tagline">One build a week. No guarantees. All code public.</p>
      </footer>
    </div>
  )
}
